on:
  push:
    branches:
      - main  # O el nombre de tu rama principal

name: deploy

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io  # Si estás usando GitHub Container Registry (si no, cambia esto al registro que estés utilizando)
          repository: ${{ github.repository }}
          tags: ${{ github.sha }}
